### ISSUE TITLE
Issue with Download Button - Not Avaliable

### ISSUE THREAD

**Issue by seval124** [fulippo/share-your-garmin-workout#1]
Looks to be new issues as the Download button is no longer available. I think this is a change by Garmin. 

Thank you for creating this app!

**Comment by seval124** [comment]
Got it Line 4 on  Share-your-workout.js needs to be fixed. 

and changed to

static getWorkoutEndpoint = 'https://connect.garmin.com/modern/workout/'

**Comment by fulippo** [comment]
Unfortunately changing the endpoint did not work. The download button is correctly injected but the workout's details are not returned. 
Garmin has added Cloudflare on top of their APIs and they are adding random seeds to the ajax requests to prevent CSRF. 
I need to figure out how to bypass the protection in order to correctly retrieve the workout details.

**Comment by seval124** [comment]
Yep - Just figuring this out. Thank you for the quick Response! :) 👍

**Comment by wjdannijs** [comment]
I still can download the workout from `dev tools` -> `network` -> `the specific workout`
Don't know how to easily translate if to the download button. Hope you can make it work.

**Comment by fulippo** [comment]
Fixed in 1.0.3
